// A single reviewed source for every guide. Check examples before producing the browser module.
import { readFileSync, writeFileSync } from 'node:fs';
import { Chess, fen as FEN, parseUci } from 'chessops';
import { legalMoves } from '../shared/puzzle-rules.js';
const book = JSON.parse(readFileSync(new URL('../content/guides.json', import.meta.url), 'utf8'));
const value = { pawn: 1, knight: 3, bishop: 3, rook: 5, queen: 9, king: 0 };
const balance = (p, color) => [...p.board].reduce((n, [, pc]) => n + value[pc.role] * (pc.color === color ? 1 : -1), 0);
let count = 0;
for (const [group, guides] of Object.entries(book)) for (const [key, guide] of Object.entries(guides)) {
  if (!guide.intro || guide.slides.length < 2) throw Error(`${group}/${key}: needs explanation and multiple examples`);
  for (const slide of guide.slides) {
    const label = `${group}/${key}/${slide.title}`;
    const check = (ok, reason) => { if (!ok) throw Error(`${label}: ${reason}`); };
    check(slide.steps.every(s => s.say), 'every step needs its own explanation');
    const setup = FEN.parseFen(slide.fen).unwrap();
    if (slide.diagram) {
      // Kingless movement diagrams still obey geometry, blockers, captures and promotion.
      const pieces = setup.board.clone();
      for (const step of slide.steps) if (step.move) for (const u of step.move.split(' ')) {
        const m = parseUci(u), pc = pieces.get(m.from), target = pieces.get(m.to);
        check(pc && target?.color !== pc.color, `missing piece or own capture ${u}`);
        const df = (m.to & 7) - (m.from & 7), dr = (m.to >> 3) - (m.from >> 3), f = Math.abs(df), r = Math.abs(dr);
        const geometry = { rook: !df || !dr, bishop: f === r, queen: !df || !dr || f === r, king: Math.max(f, r) === 1, knight: f * r === 2, pawn: target ? f === 1 && dr === (pc.color === 'white' ? 1 : -1) : !df && (dr === (pc.color === 'white' ? 1 : -1) || dr === (pc.color === 'white' ? 2 : -2) && (m.from >> 3) === (pc.color === 'white' ? 1 : 6)) }[pc.role];
        check(geometry && m.from !== m.to, `bad geometry ${u}`);
        if (pc.role !== 'knight') {
          const increment = Math.sign(df) + 8 * Math.sign(dr);
          for (let s = m.from + increment; s !== m.to; s += increment) check(!pieces.has(s), `blocked move ${u}`);
        }
        pieces.take(m.from); pieces.set(m.to, { ...pc, role: m.promotion || pc.role });
      }
      if (slide.expect === 'queens') {
        check(pieces.occupied.size() === 8, 'must show eight queens');
        for (const a of pieces.occupied) for (const b of pieces.occupied) if (a !== b)
          check((a & 7) !== (b & 7) && (a >> 3) !== (b >> 3) && Math.abs((a & 7) - (b & 7)) !== Math.abs((a >> 3) - (b >> 3)), 'queens attack each other');
      }
    } else {
      let p = Chess.fromSetup(setup).unwrap();
      const color = p.turn, start = balance(p, color);
      let first = true;
      for (const step of slide.steps) if (step.move) {
        const m = parseUci(step.move);
        check(p.isLegal(m), `illegal move ${step.move}`);
        if (first && slide.expect === 'escape') check(p.isCheck(), 'escape must start in check');
        p.play(m); first = false;
      }
      if (slide.expect === 'mate') check(p.isCheckmate(), 'example does not end in mate');
      if (slide.expect === 'stalemate') check(p.isStalemate(), 'example does not end in stalemate');
      if (slide.expect === 'check') check(p.isCheck(), 'example does not end in check');
      if (slide.expect === 'gain') check(balance(p, color) > start, 'example does not gain material');
      if (slide.expect === 'insufficient') check(p.isInsufficientMaterial(), 'material is not insufficient');
    }
    count++;
  }
}
writeFileSync(new URL('../shared/guide-content.js', import.meta.url), '// Generated by tools/build-guides.mjs from content/guides.json.\nexport const GUIDE_CONTENT = ' + JSON.stringify(book) + ';\n');
console.log(`${count} guide examples: legal moves and stated results verified`);
